name: dapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  flutter_slidable: ^2.0.0

  # State management
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3

  # Network
  web3dart: ^2.3.5
  http: ^0.13.5
  web_socket_channel: ^2.2.0

  # Encryption
  encrypt: ^5.0.1
  crypto: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - contracts/
    - assets/img/
