name: dapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_slidable: ^2.0.0

  flutter_bloc: ^8.0.1
  equatable: ^2.0.3

  web3dart: ^2.3.5
  http: ^0.13.5
  web_socket_channel: ^2.2.0

  encrypt: ^5.0.1
  crypto: ^3.0.2

  auto_route: ^5.0.2

  freezed: ^2.2.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  dartz: ^0.10.1
  uuid: ^3.0.7

  injectable: ^2.0.1
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  injectable_generator: ^2.0.1
  auto_route_generator: ^5.0.3
  lint: ^1.10.0
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true

  assets:
    - contracts/
    - assets/img/
